### ISSUE TITLE
Postcardware

### ISSUE THREAD

**Issue by tristanlatr** [lukaspustina/wpscan-analyze#10]
I'm in the process to support `wpcsan-analyze` with [WPWatcher](https://github.com/tristanlatr/WPWatcher/tree/develop) 

If you're curious , you can try it by installing `python3 -m pip install wpwatcher==2.3.0.dev6` !

**Comment by lukaspustina** [comment]
Nice! I like the integration.

If you like and give me some time, I could add markdown rendering as another output format. In this way, you could translate it into, e.g., html for nicer rendering in E-Mails.

**Comment by tristanlatr** [comment]
Yeah that would be nice,

I'll try to make an HTML email with Courrier font, I'll do the trick maybe.
Bu yeah an actual HTML <table> would be great, I don't think the table format of markdown is easily parsable tho ?

**Comment by lukaspustina** [comment]
You could use any markdown parser to transform markdown into html without having to worry about parsing the table by yourself.
The reason I suggested markdown is that you would be in control of the styling of the resulting html. If you would generate html directly, styling would become much more of a hassle. Further it's always unclear if users prefer a full html document with headers etc. or just an html snippet to include somewhere.

**Comment by tristanlatr** [comment]
Hi,

I don't think I'm going to do this, including the table text is already a major improvement. 
Emails are now wrote with Courrier font and it looks good !

<img width="680" alt="wpwatcher-report" src="https://user-images.githubusercontent.com/19967168/89569385-a0ea7980-d7f2-11ea-84ea-dd3f907ef62e.png">

**Comment by lukaspustina** [comment]
Alright. Looks nice indeed.
