### ISSUE TITLE
GLIBC_2.18 not found (required by wpscan-analyze)

### ISSUE THREAD

**Issue by tristanlatr** [lukaspustina/wpscan-analyze#4]
On Oracle linux 7.8 After installing binaries, I get: 
```bash
wpscan-analyze -h
wpscan-analyze: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by wpscan-analyze)
```
Is the GLIBC_2.18 absolutly necessary ? You cannot make it run with other version of GLIBC ? like 2.17 or previous ?

Thanks

**Comment by lukaspustina** [comment]
@tristanlatr From the previous issue I I guess you're downloading the release binary. It's build for Ubuntu Xenial by Travis. 

You could try to build `wpscan-analyse` from source following the instructions from the [Readme](https://github.com/lukaspustina/wpscan-analyze#sources). Let me know, if this fixes your problem.

**Comment by tristanlatr** [comment]
I'll try to build it from source

**Comment by tristanlatr** [comment]
Yep that's working ! thanks
